-- CreateTable
CREATE TABLE `listings` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `source` VARCHAR(32) NOT NULL,
    `external_id` VARCHAR(128) NOT NULL,
    `source_url` VARCHAR(767) NOT NULL,
    `title` VARCHAR(512) NOT NULL,
    `description` TEXT NOT NULL,
    `price_amount` DECIMAL(14, 2) NULL,
    `price_currency` CHAR(3) NULL,
    `price_per_sqm` DECIMAL(12, 2) NULL,
    `area_sqm` DECIMAL(10, 2) NULL,
    `rooms` SMALLINT NULL,
    `street` VARCHAR(512) NULL,
    `city` VARCHAR(256) NULL,
    `district` VARCHAR(256) NULL,
    `region` VARCHAR(256) NULL,
    `country` VARCHAR(128) NOT NULL,
    `image_urls_json` JSON NOT NULL,
    `attributes_json` JSON NOT NULL,
    `tags_json` JSON NULL,
    `ai_summary` TEXT NULL,
    `ai_updated_at` DATETIME(3) NULL,
    `ai_warnings_json` JSON NULL,
    `scraped_at` DATETIME(3) NOT NULL,

    UNIQUE INDEX `ux_listings_source_external`(`source`, `external_id`),
    INDEX `ix_listings_city`(`city`),
    INDEX `ix_listings_region`(`region`),
    INDEX `ix_listings_price_amount`(`price_amount`),
    INDEX `ix_listings_area_sqm`(`area_sqm`),
    INDEX `ix_listings_rooms`(`rooms`),
    INDEX `ix_listings_city_price`(`city`, `price_amount`),
    INDEX `ix_listings_source_url`(`source_url`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
