import type { Listing } from '../domain/listing.js'

/** Static fixtures — replace with DB-backed adapter later. */
export const MOCK_LISTINGS: Listing[] = [
  {
    id: 'waw-01',
    title: 'Studio near Mokotow metro',
    description: 'Bright flat, balcony, elevator.',
    priceAmount: 2800,
    priceCurrency: 'PLN',
    city: 'Warsaw',
    district: 'Mokotow',
    areaSqm: 32,
    rooms: 1,
    furnished: true,
    isNewOffer: true,
    imageUrl: null,
    sourceUrl: 'https://example.com/waw-01',
    externalId: 'ext-w01',
    createdAt: '2026-04-01T10:00:00.000Z',
  },
  {
    id: 'waw-02',
    title: '2 rooms, Old Mokotow',
    description: 'Tenement building, high ceilings.',
    priceAmount: 4200,
    priceCurrency: 'PLN',
    city: 'Warsaw',
    district: 'Mokotow',
    areaSqm: 48,
    rooms: 2,
    furnished: false,
    isNewOffer: false,
    imageUrl: null,
    sourceUrl: null,
    externalId: 'ext-w02',
    createdAt: '2026-04-02T11:00:00.000Z',
  },
  {
    id: 'waw-03',
    title: 'Wola apartment — 3 rooms',
    description: 'New development, parking included.',
    priceAmount: 5500,
    priceCurrency: 'PLN',
    city: 'Warsaw',
    district: 'Wola',
    areaSqm: 72,
    rooms: 3,
    furnished: false,
    isNewOffer: true,
    imageUrl: null,
    sourceUrl: null,
    externalId: 'ext-w03',
    createdAt: '2026-04-03T09:30:00.000Z',
  },
  {
    id: 'krk-01',
    title: 'Kazimierz — loft',
    description: 'Industrial style, large windows.',
    priceAmount: 3900,
    priceCurrency: 'PLN',
    city: 'Krakow',
    district: 'Old Town',
    areaSqm: 55,
    rooms: 2,
    furnished: true,
    isNewOffer: false,
    imageUrl: null,
    sourceUrl: null,
    externalId: 'ext-k01',
    createdAt: '2026-04-04T14:00:00.000Z',
  },
  {
    id: 'krk-02',
    title: 'Bronowice — family flat',
    description: 'Near tram, small garden.',
    priceAmount: 4600,
    priceCurrency: 'PLN',
    city: 'Krakow',
    district: 'Bronowice',
    areaSqm: 68,
    rooms: 3,
    furnished: false,
    isNewOffer: false,
    imageUrl: null,
    sourceUrl: null,
    externalId: 'ext-k02',
    createdAt: '2026-04-05T08:00:00.000Z',
  },
  {
    id: 'gdn-01',
    title: 'Gdansk Wrzeszcz — studio',
    description: 'Compact, ideal first place.',
    priceAmount: 2200,
    priceCurrency: 'PLN',
    city: 'Gdansk',
    district: 'Wrzeszcz',
    areaSqm: 28,
    rooms: 1,
    furnished: true,
    isNewOffer: true,
    imageUrl: null,
    sourceUrl: null,
    externalId: 'ext-g01',
    createdAt: '2026-04-06T12:00:00.000Z',
  },
  {
    id: 'poz-01',
    title: 'Jezyce — 2 rooms after renovation',
    description: 'New kitchen and bathroom.',
    priceAmount: 3100,
    priceCurrency: 'PLN',
    city: 'Poznan',
    district: 'Jezyce',
    areaSqm: 44,
    rooms: 2,
    furnished: false,
    isNewOffer: false,
    imageUrl: null,
    sourceUrl: null,
    externalId: 'ext-p01',
    createdAt: '2026-04-07T16:00:00.000Z',
  },
  {
    id: 'wro-01',
    title: 'Wroclaw Krzyki — flat with terrace',
    description: '12 m² terrace, storage locker.',
    priceAmount: 4800,
    priceCurrency: 'PLN',
    city: 'Wroclaw',
    district: 'Krzyki',
    areaSqm: 61,
    rooms: 3,
    furnished: false,
    isNewOffer: false,
    imageUrl: null,
    sourceUrl: null,
    externalId: 'ext-wr01',
    createdAt: '2026-04-08T10:15:00.000Z',
  },
]
